theme: jekyll-theme-cayman
title: LoL Skins Viewer
description: Map your skin collection with one simple app
show_downloads: true
latest_url: https://github.com/LeagueDevelopers/lol-skins-viewer/releases/download/v1.1.3/lol-skins-viewer-Setup-1.1.3.exe
